Update workflow

diff --git a/.github/workflows/aws-app-deployment.yml b/.github/workflows/aws-app-deployment.yml
--- a/.github/workflows/aws-app-deployment.yml
+++ b/.github/workflows/aws-app-deployment.yml
@@ -50,14 +50,13 @@ jobs:
       - name: Initialize Terraform
         run: |
           cd terraform/${{ matrix.config }}
-          terraform init
           if [[ "${{ matrix.aws_region }}" == "us-east-1" ]]; then
-            echo "1"
-          elif [[ "${{ matrix.aws_region }}" == "us-west-2" ]]
-            echo "2"
+            echo "1" | terraform init
+          elif [[ "${{ matrix.aws_region }}" == "us-west-2" ]]; then
+            echo "2" | terraform init
           else
-            echo "Invalid"
-          fi
+            echo "Invalid region provided"
+          exit 1
 
       - name: Select or Create Terraform Workspace
         run: |
